export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",
  FORBIDDEN: "FORBIDDEN",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  INVALID_ENUM: "INVALID_ENUM",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  DEADLINE_NOT_EXTENDED: "DEADLINE_NOT_EXTENDED",
  TASK_NOT_ACCEPTABLE: "TASK_NOT_ACCEPTABLE",
  RATE_LIMITED: "RATE_LIMITED",
  NETWORK_OFFLINE: "NETWORK_OFFLINE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
